### ISSUE TITLE
ENH: Multiple audio personalities

### ISSUE THREAD

**Issue by jschrempp** [BobGlicksman/Animatronics#31]
It would be nice to have several audio personalities on one SD card. For example, one could be Bob's voice, one could be Jim's voice. One might have "welcome" as the audio file for a person coming into the field of view; one might have "hey there" for the same event.

The audio files could all reside in the MP3 folder on the SD card. In the code the structure that holds information about the files would have an added "personality" attribute. On start up the firmware would load an array with the values from the structure that correspond to the active personality. The active personality would be selected by one or two jumpers on the board.

**Comment by BobGlicksman** [comment]
In addition to personality, the code structure should also have the intended event stored; i.e. the event that the file should be played for (person entered FOV, person leaves FOV, person too close, etc.).  This way, all clips associated with an event AND with a personality can be selected to play (randomly, etc.) when the event is received.
